# Schema for the configuration files of the config_template module.
config_template.settings:
  type: config_object
  label: 'config_template settings'
  mapping:
    example:
      type: string
      label: 'Example'
