<?php

use Drupal\Core\Form\FormStateInterface;

function configurationtask_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if($form_id == 'node_article_form') {
    $config = \Drupal::config('configurationtask.settings');
    $tag_name = $config->get('tags_vocabulary');


  $title = $config->get('title');
  $form['title']['widget'][0]['value']['#default_value'] = $title;
  $advanced = $config->get('advanced');
  if($advanced == 1) {
    $form['field_advanced']['widget']['value']['#default_value'] = $advanced;
  }
  $tags = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tag_name);
  $form['field_tags']['widget']['target_id']['#default_value'] = $tags;
  }
}
