<?php

/**
 * Implements hook_mail() to define email messages.
 */
function mail_cron_mail($key, &$message, $params) {
  switch ($key) {
    case 'logs_email':
      $token_service = \Drupal::token();
      $subject = $token_service->replace($params['subject'], ['node' => $params]);
      $body = $token_service->replace($params['body'], ['node' => $params]);
      $message['subject'] = $subject;
      // print_r($subject);exit;
      $message['body'][] = $body;
      break;
  }
}

/**
 * Implements hook_cron() to send emails with all contents created in the "logs" content type.
 */
function mail_cron_cron() {
  // exit;
  $last_cron_run = \Drupal::state()->get('lastcronrun');
  $current_time = time();
  //print_r($current_time);exit;

  if (empty($last_cron_run) || ($current_time - $last_cron_run) >= 1) {
    // Get all nodes of the "logs" content type.
    $query = \Drupal::entityQuery('node')
      ->condition('type', 'logs')
      ->condition('created', $last_cron_run, '>')
      ->sort('created', 'ASC')
      ->accessCheck(FALSE);
    $nids = $query->execute();

    if (!empty($nids)) {
      foreach ($nids as $nid) {
        $node = \Drupal\node\Entity\Node::load($nid);
        $token_data = ['node' => $node];
        // Load the email subject and body from mail_cron.settings.
        $subject = \Drupal::config('mail_cron.settings')->get('subject');
        $body = \Drupal::config('mail_cron.settings')->get('text');
        // print_r($subject);print_r($body);exit;

        // Replace tokens in the subject and body.
        $token_service = \Drupal::token();
        $subject = $token_service->replace($subject, $token_data);
        $body = $token_service->replace($body, $token_data);
        // print_r($subject);exit;

      // Prepare the mail parameters.
        $mail_params = [
          'subject' => $subject,
          'body' => $body,
        ];


        // Send email.
        $to = 'kmlvenkat@gmail.com'; // Change to the actual email address.
        $language_code = \Drupal::currentUser()->getPreferredLangcode();
        $params['context'] = 'logs_email';
        \Drupal::service('plugin.manager.mail')->mail('mail_cron', 'logs_email', $to, $language_code, $mail_params);
      }
    }

    // Update the last cron run timestamp.
    \Drupal::state()->set('lastcronrun', $current_time);
  }
}


